"""Event types for the timeline / event engine."""

from __future__ import annotations

from enum import StrEnum


class EventType(StrEnum):
    PERSON_ENTERED = "PERSON_ENTERED"
    PERSON_EXITED = "PERSON_EXITED"
    ZONE_ENTERED = "ZONE_ENTERED"
    ZONE_EXITED = "ZONE_EXITED"
    FACE_DETECTED = "FACE_DETECTED"
    OBJECT_DETECTED = "OBJECT_DETECTED"
    POSE_CHANGED = "POSE_CHANGED"
    VIEW_ANGLE_UPDATED = "VIEW_ANGLE_UPDATED"
    SPEECH_DETECTED = "SPEECH_DETECTED"
    RECONSTRUCTION_UPDATED = "RECONSTRUCTION_UPDATED"
    CAMERA_STARTED = "CAMERA_STARTED"
    CAMERA_STOPPED = "CAMERA_STOPPED"
    TRACKING_STARTED = "TRACKING_STARTED"
    TRACKING_ENDED = "TRACKING_ENDED"
